
title: Доп. семинары по ОКТЧ
author: 
  name: Мирошников А. В.
description: Коллекция задач и их решений
baseurl: "" 
url: "https://alicamir.github.io"

remote_theme: jekyll/minima

markdown: kramdown

minima:
  social_links:
    github: AlicaMir
    telegram: MiroshnikovAV

plugins:
  - jekyll-feed
  - jekyll-remote-theme